title: "Rust - memory and type safety"
#email: korbinian.riedhammer@fh-rosenheim.de
#description: "Materials for KP"
baseurl: ""
url: "https://matthias-prangl.github.io"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["matthias-prangl"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
