title: "Rust - memory and type safety"
url: "https://matthias-prangl.github.io/rust"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["matthias-prangl"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
